### ISSUE TITLE
Not available in online gem repositories?

### ISSUE THREAD

**Issue by glaville** [reist/firefox-json#1]
Hello

Your gem is rather awesome (I was struggling with the new LZ4 format), but the install command does not seem to be working:

> gem install firefox-json
> ERROR:  Could not find a valid gem 'firefox-json' (>= 0) in any repository
> ERROR:  Possible alternatives: firefox, firefox-data, firefox_zip

I had to install the gem manually. Would it be possible to upload/reupload it, to ease future installs for other users?

Thanks for this nice library ;)

**Comment by reist** [comment]
Hi glaville!

Sorry about the late reply - I didn't get any notification about this.
I hoped the code will be useful to someone else. Great to see it happening!

I modified the basic gem readme, but I never did publish the gem. That's now fixed. Enjoy!
